### PR TITLE
Updated gradle, changed sample app

### PR DESCRIPTION
**Pull request by muditpant13**
* Gradle update 
* Android Studio 3.0 Compaitible
* Changed Sample App.

### CODE REVIEW

**Comment by manjunathc23** [comment]
@muditpant13 : You may want to fix the CI/CD scripts as well.

**Comment by muditpant13** [comment]
@manjunathc23 Already fixed the scripts. Working fine now.. Please review..

**Comment by manjunathc23** [comment]
This was rebased and merged into master. @muditpant13 : time to bump version numbers?

**Comment by manjunathc23** [comment]
Thank you @muditpant13

**Pull request merged**
