### PR TITLE
Added screenshots to readme

### PR DESCRIPTION
**Pull request by muditpant13**
Added screen shots to readme file

### CODE REVIEW

**Comment by muditpant13** [comment]
@manjunathc23  please check if the screen shots are as we required.

**Comment by manjunathc23** [comment]
@muditpant13 : Can you please clear the notifications and generate device art using https://developer.android.com/distribute/tools/promote/device-art.html

**Comment by muditpant13** [comment]
@manjunathc23 done please check. added wrong screen shots before. :)

**Comment by manjunathc23** [comment]
This was rebased and merged into master.

**Pull request closed without merging**
